### ISSUE TITLE
Mirror to Maven Central

### ISSUE THREAD

**Issue by soundvibe** [meltwater/rxrabbit#8]
Hi,

Thanks for the great library.
Would it be possible to mirror it to Maven Central as well?
It would be much more accessible for Maven users.

**Comment by karlney** [comment]
Hi sorry for the late response and I'm glad that you find the library useful. 

We will start looking into maven central mirroring and investigate what's required.

**Comment by karlney** [comment]
I will make an attempt to follow this guide and let you know how it goes. https://www.google.se/amp/s/blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/amp/

**Comment by georgerb** [comment]
Hi,

Thanks bro for the great library, whats required to mirror with Maven Central and how can I help you out with that?

**Comment by karlney** [comment]
Hi @georgerb this got stuck on the fact that I am not admin on our Bintray account, and then I forgot about it. I will ask our infrastructure team about this again.

**Comment by karlney** [comment]
Some progress is made:  https://issues.sonatype.org/browse/OSSRH-36133

**Comment by karlney** [comment]
It seems that we don't upload javadoc currently (I thought we were). And that is required: http://central.sonatype.org/pages/requirements.html  before maven central accepts the artifacts.

I will add that to the next release.

**Comment by karlney** [comment]
Almost done:

I just need to get in this info into the POM file:

Project name , 
Project description , 
Project URL , 
License information missing, SCM URL , 
Developer information

**Comment by karlney** [comment]
And now version 1.3.0 is available on Maven Central

https://oss.sonatype.org/#nexus-search;quick~rxrabbit
